title: "FX's Projects"
name: "François Perron"
description: "Musings involving electronics, systems, and stuff I care about."
baseurl: "/fx-portfolio" # Leave this empty for the root
url: "https://fperron-kt88.github.io"
google_analytics: "G-xxxxxxxxxx"

#author:
#  name: "François Perron"
#  avatar: "/assets/images/avatar.jpg"
#  bio: "Hacker at heart, avid learner. I build systems."

# Custom variables for GitHub
github:
  repository_url: "https://github.com/fperron-kt88/fx-portfolio"
  zip_url: "https://github.com/fperron-kt88/fx-portfolio/archive/refs/heads/main.zip"
  tar_url: "https://github.com/fperron-kt88/fx-portfolio/archive/refs/heads/main.tar.gz"
  owner_url: "https://github.com/fperron-kt88"
  owner_name: "François Perron"
  project_tagline: "Hosted on GitHub Pages"
  build_revision: "v1.0" # Example revision

# Show downloads toggle
#show_downloads: true

sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# Site language
lang: "en-US"

# Navigation Links
nav_links:
  - title: "Home"
    url: "/"
  - title: "Portfolio"
    url: "/portfolio/"
  - title: "About"
    url: "/about/"

# Recognize _pages directory
collections:
  pages:
    output: true
    permalink: /:path/

